### ISSUE TITLE
Wrong images shown when projects clicked

### ISSUE THREAD

**Issue by bryszard** [AgileVentures/av-ghost-theme#10]
I've just looked over the static website and found that when I click on Project Unify, Lookup and Snow Angels the image I see is LocalSupport's page. 

![project unify](https://cloud.githubusercontent.com/assets/12682792/15433321/2b3fac76-1eb2-11e6-9c32-8be4086a2a45.png)

**Comment by tansaku** [comment]
thanks @bryszard - actually that's an issue on this repo https://github.com/AgileVentures/av-static-website/issues/13 thanks for flagging it :-)
